# Generated by Django 4.0.5 on 2022-06-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_video_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pdatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
