# Generated by Django 4.0.5 on 2022-06-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_video_pdatetime_video_pdate_video_ptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='pdate',
        ),
        migrations.RemoveField(
            model_name='video',
            name='ptime',
        ),
        migrations.AddField(
            model_name='video',
            name='pdatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
